### PR TITLE
Featured images remapping and better tag import

### PR DESCRIPTION
**Pull request by lineupboekenmedia**
I've added support for the remapping of featured images. There was non working code in the class and I made it working

I also added some code that handle terms better. I sort of copied the code from the old importer. If the term is missing in the importfile, the code will check if it can't find the term by its slug in the database and link the post to this term. If the term isn't found a new term is created based on the info of the post in the import file.

Could you merge the changes in the main repo?

### CODE REVIEW

**Comment by rmccue** [comment]
@lineupboekenmedia Thanks for the PR, and sorry for the delay in getting to this.

Can you split these up into separate PRs please? Separate features/bugs should be separated. Happy to merge the featured images change straight away, but need to look further into the term changes here.

**Comment by lineupboekenmedia** [comment]
I'll will try to find some time to separate the features.  I'm busy with other projects and not very experienced with git(hub).  So I need some time. :-)

**Comment by lineupboekenmedia** [comment]
Split the changes into two pull requests: #104 and #105

**Comment by lineupboekenmedia** [comment]
Closing this request. Use #104 and #105 from now on

**Pull request closed without merging**
