### PR TITLE
Add support for Composer

### PR DESCRIPTION
**Pull request by franz-josef-kaiser**
This PR adds two things

1. Support for _Composer_ via a `composer.json` file
1. `.gitignore` file with _very_ basic ignore rules

### CODE REVIEW

**Comment by franz-josef-kaiser** [comment]
Detailed information about that change can be found [here](https://github.com/humanmade/WordPress-Importer/pull/21/files).

**Comment by swissspidy** [comment]
👋 

Some notes:

* I'd open a separate PR for the `.gitignore` file, as it's not related to the composer support.  
 After that, in this PR the `vendor` folder could be added to the `.gitignore` file.
* The license in the `composer.json` file is wrong. It's GPLv2 or later, not MIT license.
* Is `"extra"` needed?
* I wouldn't add individual people as authors, but  instead _WordPress.org_ or maybe _Human Made Limited_ (see https://github.com/humanmade/Custom-Meta-Boxes/blob/master/composer.json).
* Also, I wouldn't add Ryan's email address as a support option.
* Should the `"name"` be `humanmade/WordPress-Importer` for now instead of `wordpress/importer`?

**Comment by franz-josef-kaiser** [comment]
Some answers:

 * `.gitignore`: No, this is not a separate PR, but agree that `/vendor` is missing
 * license: check
 * `extra` alias: see [docs for `branch-alias`](https://getcomposer.org/doc/articles/aliases.md) – tl;dr: Else branches are not comparable
 * `extra` installers: see [docs for composer installers](https://github.com/composer/installers). Else everything ends up in the `wp` dir, which is just a package and preferably installed _alongside_ wp and not into each other
 * `name`: I'd rather name it `humanmade/importer` as other paths are slightly more difficult to handle with tab autocomplete in the CLI, etc.
 * Support: There's no other maintainer mentioned so far
 * `authors`: are humans and not a company that has _human_ as part of their name. anyway, as long as their's no `AUTHORS.txt` or similar file shipped with it, I'd just stuff the list there or use that place in the json to link to the list of contributors

Anyway, please feel free to build on top of this PR and alter whatever you feel fits best.

**Comment by rmccue** [comment]
> Support: There's no other maintainer mentioned so far

My personal email isn't a support forum :)

> I'd just stuff the list there or use that place in the json to link to the list of contributors

Let's link to https://github.com/humanmade/WordPress-Importer/graphs/contributors

**Comment by ntwb** [comment]
The `name` should be `humanmade/wordpress-importer` as that is the plugin slug:
https://plugins.trac.wordpress.org/browser/wordpress-importer

**Comment by franz-josef-kaiser** [comment]
- [x] @rmccue mail removed
- [x] Name now is `humanmade/wordpress-importer` even if it is annoying
- [x] Keywords added for packagist
- [x] Support routes extended by a link to this issues
- [x] Authors link now points to contributors list
- [x] The `/vendor` folder is ignores
- [x] License set to GPLv2

**Comment by rmccue** [comment]
Wonderful, thanks, and sorry for the delay. :)

**Pull request merged**
